services:
  mongo1:
    image: mongo:4
    command: mongod --replSet rs0 --bind_ip_all
    container_name: app_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  mongo2:
    image: mongo:4
    command: mongod --replSet rs0 --bind_ip_all
    restart: always
    volumes:
      - ./data2:/data/db
    networks:
      - mongo-network

  mongo3:
    image: mongo:4
    command: mongod --replSet rs0 --bind_ip_all
    restart: always
    volumes:
      - ./data3:/data/db
    networks:
      - mongo-network


networks:
  mongo-network:
